"""Fix decree type

Revision ID: 197061fc1c4d
Revises: a9239ab529da
Create Date: 2022-05-27 06:17:31.052935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197061fc1c4d'
down_revision = 'a9239ab529da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
