"""Add eds

Revision ID: 2788d6239e60
Revises: d4867f3a4c0a
Create Date: 2022-05-24 07:01:29.242214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2788d6239e60'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('providerTypeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eds', 'eds_provider_type', ['providerTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eds', type_='foreignkey')
    op.drop_column('eds', 'providerTypeId')
    # ### end Alembic commands ###
