"""Edit decree model

Revision ID: 36bee59d4f75
Revises: 197061fc1c4d
Create Date: 2022-05-27 06:25:27.891245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bee59d4f75'
down_revision = '197061fc1c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
