"""Add eds

Revision ID: 6969539492b2
Revises: b2fea017b6be
Create Date: 2022-05-24 07:04:53.461081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6969539492b2'
down_revision = 'b2fea017b6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'eds', 'eds_provider_type', ['providerTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eds', type_='foreignkey')
    # ### end Alembic commands ###
