"""FIX ALL

Revision ID: 93342560e06e
Revises: 6969539492b2
Create Date: 2022-05-24 07:10:09.673121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93342560e06e'
down_revision = '6969539492b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('signatureId', sa.Integer(), nullable=True))
    op.alter_column('eds', 'providerTypeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_eds_signatureId'), 'eds', ['signatureId'], unique=False)
    op.create_foreign_key(None, 'eds', 'signature', ['signatureId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eds', type_='foreignkey')
    op.drop_index(op.f('ix_eds_signatureId'), table_name='eds')
    op.alter_column('eds', 'providerTypeId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('eds', 'signatureId')
    # ### end Alembic commands ###
