"""Fix decree type

Revision ID: a9239ab529da
Revises: abd21b5eede4
Create Date: 2022-05-27 06:11:29.586720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9239ab529da'
down_revision = 'abd21b5eede4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
