"""Add eds

Revision ID: b2fea017b6be
Revises: f55e22a70f1e
Create Date: 2022-05-24 07:03:36.321796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fea017b6be'
down_revision = 'f55e22a70f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('providerTypeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eds', 'eds_provider_type', ['providerTypeId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eds', type_='foreignkey')
    op.drop_column('eds', 'providerTypeId')
    # ### end Alembic commands ###
