"""FIX ALL

Revision ID: eafd034cd17e
Revises: abd6bf46526d
Create Date: 2022-05-24 07:20:44.899678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafd034cd17e'
down_revision = 'abd6bf46526d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
