"""Add eds

Revision ID: f55e22a70f1e
Revises: 2788d6239e60
Create Date: 2022-05-24 07:01:59.517838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55e22a70f1e'
down_revision = '2788d6239e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eds', 'providerTypeId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('providerTypeId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
